### PR TITLE
LPS-81613 Space of 16px between the checkboxes and radio buttons when it is form build field

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60211. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
