### PR TITLE
LPS-97374

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @alinedoleron,

Attached is an update for http://issues.liferay.com/browse/LPS-97374.

This issue was originally flagged for only 7.1.x, but upon further inspection, I think we can make the change on master and backport this issue, since the CSS on master is now rendered using clay so the changes do not affect anything.

The changes were originally made with Git SHA ID: 2345d80156885ae3bf6df428478d557707182240

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Hi @ jonmak08,

Sorry for the delay.
The change does not affect the master, so we can do that. =)
I'll forward the PR to Brian.

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75127. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonmak08** [comment]
Thanks @alinedoleron!

**Pull request closed without merging**
