### PR TITLE
LPS-122220 SF non related to the ticket but catched during formatSource

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:app-builder

**Comment by alinedoleron** [comment]
@carolmariaabb

**Comment by carolmariaabb** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
