### PR TITLE
LPS-82723 Adjust the padding to 24px

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
LGTM

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:stop

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Pull request forwarded to https://github.com/jeyvison/liferay-portal/pull/68. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
