### PR TITLE
LPS-80349 make required message closer to grid field

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @rafaprax

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
LGTM!

**Comment by alinedoleron** [comment]
Pull request forwarded to https://github.com/rafaprax/liferay-portal/pull/572. [See changes here.](https://github.com/alinedoleron/liferay-portal/compare/44526b08b8e2~4...44526b08b8e2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/58008

**Pull request closed without merging**
