### PR TITLE
LPS-81593 Adjust the border color, the border-radius and delete the shadow

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
LGTM

**Comment by alinedoleron** [comment]
Failures not related to the fix.

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59944. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60144. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
