### PR TITLE
LPS-180059

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-180059

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Review by danvb112 — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/132586

**Pull request closed without merging**
