### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by alinedoleron** [comment]
LGTM

**Comment by alinedoleron** [comment]
ci:test

**Comment by brunobasto** [comment]
@clovisdasilvaneto this method: https://github.com/clovisdasilvaneto/liferay-portal/blob/0b77b85c3f233abc0110dd3478eeb2fcc6159df6/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-builder/src/main/resources/META-INF/resources/js/form_builder_field_support.js#L92

should prevent generating fields with duplicated names, have looked at it?

**Comment by clovisdasilvaneto** [comment]
@brunobasto Yes, I've looked but the problem happened before the call of this method, I've seen that the forms call this method 3 times when user clicks in any field.

**Pull request closed without merging**
