### PR TITLE
LPS-80078 Fix delete button position from Options Field

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
@alinedoleron , I still have some issues on this :( Please, take a look when you have time. :)

screen shot 2018-05-28 at 5 25 44 pm
screen shot 2018-05-28 at 5 25 34 pm

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/pedroqueiroz/liferay-portal/pull/158. [See changes here.](https://github.com/alinedoleron/liferay-portal/compare/01f12950a8c6~3...01f12950a8c6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
