### PR TITLE
LPS-81594 Moving help text right below the field

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @marcelabc, please, could you try to reproduce this poshi steps to check if it's related to the fix?LocalFile.Forms#SubmitFormWithUploadField 
Thanks

**Comment by marcelabc** [comment]
Hi @vicnate5, could you look if it is related to the fix please? i tried to replicate the fail test but I am not sure if I did it right

**Comment by vicnate5** [comment]
I will check this.

**Comment by vicnate5** [comment]
@marcelabc @alinedoleron This is OK.

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60164. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60166. [See changes here.](https://github.com/alinedoleron/liferay-portal/compare/5945d089fe3c~1...5945d089fe3c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
