### PR TITLE
LPS-81613 Add wrapper in these classes to not affect in general components

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60895. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
