### PR TITLE
LPS-122220 Avoid code duplication.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:test:app-builder

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
> ### ❌ ci:test:app-builder - 6 out of 10 jobs passed in 1 hour 44 minutes
> Click here for more details.

@natocesarrego, I believe those failures are not related to our the code.

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
