### PR TITLE
LPS-123777 Send new property to component

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://issues.liferay.com/browse/LPS-123777

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by liferay-forms** [comment]
Hey @carolmariaabb, can you please fix the source formatter issues and resend? Thanks

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/natocesarrego/liferay-portal/pull/924. [See changes here.](https://github.com/alinedoleron/liferay-portal/compare/614fc4ad11d3~2...614fc4ad11d3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
