### PR TITLE
LPS-98878 Fix labels with correct locale in form display

### PR DESCRIPTION
**Pull request by mclomello**
@alinedoleron could u review this pr?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/alinedoleron/liferay-portal/pull/94. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/alinedoleron/liferay-portal/pull/95. [See changes here.](https://github.com/alinedoleron/liferay-portal/compare/54d5fd547a26~1...54d5fd547a26) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
Pull request submitted to https://github.com/mclomello/liferay-portal/pull/7. [See changes here.](https://github.com/alinedoleron/liferay-portal/compare/54d5fd547a26~1...54d5fd547a26) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
