### PR TITLE
LPS-119393 Add id to DDM Form Report Portlet container in order to access it on JavaScript.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
Hi @natocesarrego. Looks good to me!

**Comment by natocesarrego** [comment]
@alinedoleron, please be aware of these changes to our future development. 😉 Besides, if the relevant suite succeeds, please forward this pull to Brian through `ci:forward`.

Thanks.

**Comment by alinedoleron** [comment]
ci:forward

**Pull request closed without merging**
