### PR TITLE
LPS-120211 Close actions DropDown when another field is focused

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by alinedoleron** [comment]
Hi, Gabriel!! Looks good!!

**Comment by gabrielwas** [comment]
@interaminense FYI

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
